# Randomization of trials

In [1]:
[f"RandomDot{i}.png" for i in range(1, 43)]

['RandomDot1.png',
 'RandomDot2.png',
 'RandomDot3.png',
 'RandomDot4.png',
 'RandomDot5.png',
 'RandomDot6.png',
 'RandomDot7.png',
 'RandomDot8.png',
 'RandomDot9.png',
 'RandomDot10.png',
 'RandomDot11.png',
 'RandomDot12.png',
 'RandomDot13.png',
 'RandomDot14.png',
 'RandomDot15.png',
 'RandomDot16.png',
 'RandomDot17.png',
 'RandomDot18.png',
 'RandomDot19.png',
 'RandomDot20.png',
 'RandomDot21.png',
 'RandomDot22.png',
 'RandomDot23.png',
 'RandomDot24.png',
 'RandomDot25.png',
 'RandomDot26.png',
 'RandomDot27.png',
 'RandomDot28.png',
 'RandomDot29.png',
 'RandomDot30.png',
 'RandomDot31.png',
 'RandomDot32.png',
 'RandomDot33.png',
 'RandomDot34.png',
 'RandomDot35.png',
 'RandomDot36.png',
 'RandomDot37.png',
 'RandomDot38.png',
 'RandomDot39.png',
 'RandomDot40.png',
 'RandomDot41.png',
 'RandomDot42.png']

In [2]:
import pandas as pd
import random

DVs = [0, 1, 2, 3]  # Initialize DVs list
buttons = {0: ["Greater", "Smaller"], 1: ["Smaller", "Greater"]}  # Define buttons dictionary
conditions = {0: "both_right", 1: "both_wrong", 2: "only_sub_right", 3: "only_sub_wrong"}  # Define conditions dictionary
dotimg = [f"RandomDot{i}.png" for i in range(1, 41)]  # Create list of dot images
repeat = 6  # Define repeat value

# Initialize empty DataFrame for the result table
tb = pd.DataFrame({
    "type_trial": [], "stipic": [], "DV": [],
    "dotlefttext": [], "dotrighttext": [], "picture": [],
    "answer": [], "number": []
})

# Generate experimental trials
for key, value in conditions.items():
    for DV in DVs:
        for button in buttons.values():
            for rep in range(repeat):
                tb = tb.append({
                    'type_trial': key,
                    'stipic': value + ".png",
                    'DV': DV,
                    'dotlefttext': button[0],
                    'dotrighttext': button[1],
                    'picture': random.choice(dotimg),
                    'answer': "No answer",
                    'number': 20 + random.randint(-1, 1)
                }, ignore_index=True)

print(tb)

     type_trial              stipic   DV dotlefttext dotrighttext  \
0           0.0      both_right.png  0.0     Greater      Smaller
1           0.0      both_right.png  0.0     Greater      Smaller
2           0.0      both_right.png  0.0     Greater      Smaller
3           0.0      both_right.png  0.0     Greater      Smaller
4           0.0      both_right.png  0.0     Greater      Smaller
..          ...                 ...  ...         ...          ...
187         3.0  only_sub_wrong.png  3.0     Smaller      Greater
188         3.0  only_sub_wrong.png  3.0     Smaller      Greater
189         3.0  only_sub_wrong.png  3.0     Smaller      Greater
190         3.0  only_sub_wrong.png  3.0     Smaller      Greater
191         3.0  only_sub_wrong.png  3.0     Smaller      Greater

             picture     answer  number
0     RandomDot7.png  No answer    21.0
1    RandomDot34.png  No answer    21.0
2    RandomDot14.png  No answer    21.0
3    RandomDot24.png  No answer    20.0
4    RandomDot33.png  No answer    20.0
..               ...        ...     ...
187   RandomDot4.png  No answer    20.0
188  RandomDot27.png  No answer    20.0
189  RandomDot26.png  No answer    21.0
190  RandomDot10.png  No answer    19.0
191   RandomDot5.png  No answer    20.0

[192 rows x 8 columns]

In [3]:
# attention check
repeat = 3
for this_type in [4,5]:
    for bk, button in buttons.items():
        for rep in range(repeat):
            answer = "LeftButton" if ((this_type == 4 and bk == 0) or (this_type == 5 and bk == 1)) else "RightButton"
            number = 5 if this_type==4 else 20 + random.randint(-1, 1)
            tb = tb.append({
                            'type_trial': this_type,
                            'stipic': "both_right.png",
                            'DV': 10,
                            'dotlefttext': button[0],
                            'dotrighttext': button[1],
                            'picture': f"RandomDot{37+this_type}.png",
                            'answer': answer,
                            'number': number
                        }, ignore_index=True)
tb.tail(10)

,type_trial,stipic,DV,dotlefttext,dotrighttext,picture,answer,number
194,4.0,both_right.png,10.0,Greater,Smaller,RandomDot41.png,LeftButton,5.0
195,4.0,both_right.png,10.0,Smaller,Greater,RandomDot41.png,RightButton,5.0
196,4.0,both_right.png,10.0,Smaller,Greater,RandomDot41.png,RightButton,5.0
197,4.0,both_right.png,10.0,Smaller,Greater,RandomDot41.png,RightButton,5.0
198,5.0,both_right.png,10.0,Greater,Smaller,RandomDot42.png,RightButton,21.0
199,5.0,both_right.png,10.0,Greater,Smaller,RandomDot42.png,RightButton,20.0
200,5.0,both_right.png,10.0,Greater,Smaller,RandomDot42.png,RightButton,20.0
201,5.0,both_right.png,10.0,Smaller,Greater,RandomDot42.png,LeftButton,19.0
202,5.0,both_right.png,10.0,Smaller,Greater,RandomDot42.png,LeftButton,21.0
203,5.0,both_right.png,10.0,Smaller,Greater,RandomDot42.png,LeftButton,21.0

In [4]:
# tb.to_csv("condition.csv", index=False)

In [5]:
tb.shape

(204, 8)

In [8]:
# for each subject, randomly choose 3 trials from each condition and 1 trial from the attention check
# experimental design - practice
import random as random
pracrow = random.sample(range(10), 3)

# exp design - formal procedure
chunks = [range(i, i+12) for i in range(0, 192, 12)]
chunks.append(range(192, 198)) # attention check: trial_type = 4
chunks.append(range(198, 204)) # attention check: trial_type = 5

# Initialize a list to store the selected trials
chooserow = []

# For the both_right condition, randomly choose 1 trials from each DV
for chunk in chunks[:4]:
    choose = random.sample(chunk, 1)
    chooserow.extend(choose)
    print(f"experiment: {chunk}, choose: {choose}")

# Randomly choose items from the first 16 chunks (3 items per chunk)
for chunk in chunks[4:len(chunks)-2]:
    choose = random.sample(chunk, 3)
    print(f"experiment: {chunk}, choose: {choose}")
    chooserow.extend(choose)

# Randomly choose items from the last 2 chunks (1 item per chunk)
for chunk in chunks[len(chunks)-2:]:
    choose = random.sample(chunk, 1)
    chooserow.extend(choose)
    print(f"experiment: {chunk}, choose: {choose}")

tb.loc[chooserow, :]

chooserow = random.sample(chooserow, len(chooserow))
for i in range(0, len(chooserow)-2): # pseudo-randomize the order of the trials to make sure that the same condition does not appear consecutively
    while chooserow[i] //12 % 4 == chooserow[i+1] // 12 % 4 == chooserow[i+2] // 12 % 4:
        tail = chooserow[range(i+2, len(chooserow))]
        newtail = random.sample(tail, len(tail))
        chooserow = chooserow[range(i+2)] + newtail

print(f"chooserow: {chooserow}")

experiment: range(0, 12), choose: [9]
experiment: range(12, 24), choose: [20]
experiment: range(24, 36), choose: [25]
experiment: range(36, 48), choose: [45]
experiment: range(48, 60), choose: [51, 53, 55]
experiment: range(60, 72), choose: [67, 69, 68]
experiment: range(72, 84), choose: [83, 74, 78]
experiment: range(84, 96), choose: [91, 92, 93]
experiment: range(96, 108), choose: [101, 98, 96]
experiment: range(108, 120), choose: [109, 111, 110]
experiment: range(120, 132), choose: [120, 129, 130]
experiment: range(132, 144), choose: [134, 136, 132]
experiment: range(144, 156), choose: [155, 154, 153]
experiment: range(156, 168), choose: [160, 159, 165]
experiment: range(168, 180), choose: [169, 170, 168]
experiment: range(180, 192), choose: [182, 184, 191]
experiment: range(192, 198), choose: [192]
experiment: range(198, 204), choose: [203]

,type_trial,stipic,DV,dotlefttext,dotrighttext,picture,answer,number
9,0.0,both_right.png,0.0,Smaller,Greater,RandomDot4.png,No answer,19.0
20,0.0,both_right.png,1.0,Smaller,Greater,RandomDot21.png,No answer,21.0
25,0.0,both_right.png,2.0,Greater,Smaller,RandomDot32.png,No answer,19.0
45,0.0,both_right.png,3.0,Smaller,Greater,RandomDot22.png,No answer,21.0
51,1.0,both_wrong.png,0.0,Greater,Smaller,RandomDot22.png,No answer,19.0
53,1.0,both_wrong.png,0.0,Greater,Smaller,RandomDot30.png,No answer,19.0
55,1.0,both_wrong.png,0.0,Smaller,Greater,RandomDot10.png,No answer,21.0
67,1.0,both_wrong.png,1.0,Smaller,Greater,RandomDot37.png,No answer,19.0
69,1.0,both_wrong.png,1.0,Smaller,Greater,RandomDot4.png,No answer,19.0
68,1.0,both_wrong.png,1.0,Smaller,Greater,RandomDot25.png,No answer,20.0
83,1.0,both_wrong.png,2.0,Smaller,Greater,RandomDot22.png,No answer,20.0
74,1.0,both_wrong.png,2.0,Greater,Smaller,RandomDot7.png,No answer,20.0
78,1.0,both_wrong.png,2.0,Smaller,Greater,RandomDot11.png,No answer,21.0
91,1.0,both_wrong.png,3.0,Smaller,Greater,RandomDot4.png,No answer,19.0
92,1.0,both_wrong.png,3.0,Smaller,Greater,RandomDot32.png,No answer,20.0
93,1.0,both_wrong.png,3.0,Smaller,Greater,RandomDot31.png,No answer,21.0
101,2.0,only_sub_right.png,0.0,Greater,Smaller,RandomDot7.png,No answer,19.0
98,2.0,only_sub_right.png,0.0,Greater,Smaller,RandomDot6.png,No answer,20.0
96,2.0,only_sub_right.png,0.0,Greater,Smaller,RandomDot5.png,No answer,19.0
109,2.0,only_sub_right.png,1.0,Greater,Smaller,RandomDot39.png,No answer,19.0
111,2.0,only_sub_right.png,1.0,Greater,Smaller,RandomDot20.png,No answer,20.0
110,2.0,only_sub_right.png,1.0,Greater,Smaller,RandomDot40.png,No answer,21.0
120,2.0,only_sub_right.png,2.0,Greater,Smaller,RandomDot8.png,No answer,21.0
129,2.0,only_sub_right.png,2.0,Smaller,Greater,RandomDot3.png,No answer,19.0
130,2.0,only_sub_right.png,2.0,Smaller,Greater,RandomDot3.png,No answer,21.0
134,2.0,only_sub_right.png,3.0,Greater,Smaller,RandomDot40.png,No answer,20.0
136,2.0,only_sub_right.png,3.0,Greater,Smaller,RandomDot4.png,No answer,20.0
132,2.0,only_sub_right.png,3.0,Greater,Smaller,RandomDot28.png,No answer,20.0
155,3.0,only_sub_wrong.png,0.0,Smaller,Greater,RandomDot19.png,No answer,21.0
154,3.0,only_sub_wrong.png,0.0,Smaller,Greater,RandomDot11.png,No answer,20.0
153,3.0,only_sub_wrong.png,0.0,Smaller,Greater,RandomDot25.png,No answer,19.0
160,3.0,only_sub_wrong.png,1.0,Greater,Smaller,RandomDot29.png,No answer,21.0
159,3.0,only_sub_wrong.png,1.0,Greater,Smaller,RandomDot38.png,No answer,21.0
165,3.0,only_sub_wrong.png,1.0,Smaller,Greater,RandomDot13.png,No answer,20.0
169,3.0,only_sub_wrong.png,2.0,Greater,Smaller,RandomDot13.png,No answer,19.0
170,3.0,only_sub_wrong.png,2.0,Greater,Smaller,RandomDot6.png,No answer,20.0
168,3.0,only_sub_wrong.png,2.0,Greater,Smaller,RandomDot2.png,No answer,19.0
182,3.0,only_sub_wrong.png,3.0,Greater,Smaller,RandomDot23.png,No answer,21.0
184,3.0,only_sub_wrong.png,3.0,Greater,Smaller,RandomDot24.png,No answer,19.0
191,3.0,only_sub_wrong.png,3.0,Smaller,Greater,RandomDot5.png,No answer,20.0
192,4.0,both_right.png,10.0,Greater,Smaller,RandomDot41.png,LeftButton,5.0
203,5.0,both_right.png,10.0,Smaller,Greater,RandomDot42.png,LeftButton,21.0

In [16]:
10/3
10//3 % 4

3

In [27]:
# shuffle chooserow and make sure there are no consecutive items from the same condition (chooserow[i-1] % 12 = chooserow[i] % 12 = chooserow[i+1] % 12)
chooserow = random.sample(chooserow, len(chooserow))
print(f"length of chooserow: {len(chooserow)}")
tb.loc[chooserow, :]
for i in range(len(chooserow) - 2):  # Iterate over the entire length of chooserow
    while i < len(chooserow) - 2 and chooserow[i] // 12 % 4 == chooserow[i+1] // 12 % 4 == chooserow[i+2] // 12 % 4:
        tail = chooserow[i+2:]
        newtail = random.sample(tail, len(tail))
        chooserow = chooserow[:i+2] + newtail  # Update chooserow properly

# tb.loc[chooserow, :]
print(f"length of chooserow: {len(chooserow)}")

length of chooserow: 42
length of chooserow: 42